# =================================================================
#
# Authors: Benjamin Webb <bwebb@lincolninst.edu>
#
# Copyright (c) 2023 Benjamin Webb
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
  bind:
    host: 0.0.0.0 #change to your hostname if running your own instance
    port: 80
  url: ${PYGEOAPI_URL} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    # First language is the default language
    - en-US
    - fr-CA
  # cors: true
  pretty_print: true
  limit: 100
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'
  # templates:
  # path: /path/to/Jinja2/templates
  # static: /path/to/static/folder # css/js/img
  # ogc_schemas_location: /opt/schemas.opengis.net

logging:
  level: ERROR

metadata:
  identification:
    title: NHGF fabric with pygeoapi
    description: NHGF fabric with pygeoapi
    keywords: &keywords
      - census
      - nhgf
      - iow
      - geospatial
      - api
      - pygeoapi
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/internetofwater/geoconnex.us
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Center for Geospatial Solutions
    url: http://cgs.earth/
  contact:
    name: Webb, Benjamin
    position: Software Developer
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: bwebb@lincolninst.edu
    url: https://internetofwater.org
    role: pointOfContact

resources:
  Census-Points-2020:
    type: collection
    title: NHGF Census Points 2020
    description: NHGF Census Points 2020
    keywords: *keywords
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://cgsfilestore.blob.core.windows.net/publicshare/2020Censuspts.gpkg
        hreflang: en-US
    extents: &extents
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: null
        end: null
    providers:
      - type: feature
        name: PostgreSQL
        data: &provider-data
          host: ${POSTGRES_HOST}
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
        id_field: objectid
        table: 2020censuspts
        # uri_field: uri
        geom_field: shape
  Census-Blocks-2020:
    type: collection
    title: NHGF Census Blocks 2020
    description: NHGF Census Blocks 2020
    keywords: *keywords
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://cgsfilestore.blob.core.windows.net/publicshare/2020Censusblocks.gpkg
        hreflang: en-US
    extents: *extents
    providers:
      - type: feature
        name: PostgreSQL
        data: *provider-data
        id_field: geoid20
        table: 2020censusblocks
        geom_field: shape
  Census-Polygons-2020:
    type: collection
    title: NHGF Census Polygons 2020
    description: NHGF Census Polygons 2020
    keywords: *keywords
    links:
      - type: application/html
        rel: canonical
        title: data source
        href: https://cgsfilestore.blob.core.windows.net/publicshare/2020Censuspoly.gpkg
        hreflang: en-US
    extents: *extents
    providers:
      - type: feature
        name: PostgreSQL
        data: *provider-data
        id_field: objectid
        table: 2020censuspoly
        # uri_field: uri
        geom_field: shape
