# =================================================================
#
# Authors: Benjamin Webb <bwebb@lincolninst.edu>
#
# Copyright (c) 2023 Benjamin Webb
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
  bind:
    host: 0.0.0.0 #change to your hostname if running your own instance
    port: 80
  url: ${PYGEOAPI_URL} #change to host URL  if running your own instance
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: true
  languages:
    # First language is the default language
    - en-US
    - fr-CA
  # cors: true
  pretty_print: false
  limit: 100
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '<a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>'
  # templates:
  #   path: /path/to/Jinja2/templates
  #   static: /path/to/static/folder # css/js/img
  # ogc_schemas_location: /opt/schemas.opengis.net
  # manager: # optional OGC API - Processes asynchronous job management
  #   name: TinyDB # plugin name (see pygeoapi.plugin for supported process_manager's)
  #   connection: /tmp/pygeoapi-process-manager.db # connection info to store jobs (e.g. filepath)
  #   output_dir: /tmp/ # temporary file area for storing job results (files)

logging:
  level: INFO

metadata:
  identification:
    title: NHDPlusV2 Census Intersection
    description: National Hydrography Dataset Plus (NHDPlusV2) with Census intersection
    keywords: &keywords
      - nhgfpv2
      - geofabric
      - hydrography
      - census geography
      - census
      - iow
      - geospatial
      - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://github.com/internetofwater/nhgf-census
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Center for Geospatial Solutions
    url: http://cgs.earth/
  contact:
    name: Webb, Benjamin
    position: Software Developer
    address: 113 Brattle St
    city: Cambridge
    stateorprovince: Massachussetts
    postalcode: 02138
    country: USA
    email: bwebb@lincolninst.edu
    url: https://internetofwater.org
    role: pointOfContact

resources:
  "2000":
    type: collection
    title: NHDPlusV2 for the 2000 Census
    description: NHDPlusV2 intersected with 2000 Census polygons
    keywords: *keywords
    links:
      - &data-source
        type: application/html
        rel: canonical
        title: data source
        href: https://storage.googleapis.com/nhgf/2000CensusPolys.gpkg
        hreflang: en-US
    extents: &extents
      spatial:
        bbox: [-170, 15, -51, 72]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
      temporal:
        begin: null
        end: null
    providers:
      - &provider
        type: feature
        name: PostgreSQL
        data:
          host: ${POSTGRES_HOST}
          dbname: ${POSTGRES_DB}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
        table: 2000censuspolys
        id_field: id
        uri_field: uri
        geom_field: shape
  "2010":
    type: collection
    title: NHDPlusV2 for the 2010 Census
    description: NHDPlusV2 intersected with 2010 Census polygons
    keywords: *keywords
    links:
      - <<: *data-source
        href: https://storage.googleapis.com/nhgf/2010CensusPolys.gpkg
    extents: *extents
    providers:
      - <<: *provider
        table: 2010censuspolys
  "2020":
    type: collection
    title: NHDPlusV2 for the 2020 Census
    description: NHDPlusV2 intersected with 2020 Census polygons
    keywords: *keywords
    links:
      - <<: *data-source
        href: https://storage.googleapis.com/nhgf/2020CensusPolys.gpkg
    extents: *extents
    providers:
      - <<: *provider
        table: 2020censuspolys
  intersector:
    type: process
    processor:
      name: GeoIntersector
    title: Census Intersection Processs
    description: A process that takes a URL of a geoJSON, and returns all intersections.
    keywords: *keywords
    links:
      - <<: *data-source
        href: https://storage.googleapis.com/nhgf/
